### ISSUE TITLE
hide process name from ps / top?

### ISSUE THREAD

**Issue by nyxaria** [liberize/ssc#10]
Hi, love the project, thank you so much for it!

I am trying to use this to hide a process from myself such that I cannot kill it. Using this project I was able to get rid of the script name being listed (and greppable) in `ps` output. However, all processes spawned that were compiled using `ssc` are now called `/bin/zsh /dev/fd/3`. Is there any way I can change this? Ideally I would set it to a random string that mimic or closely resemble existing processes on my PC.

<img width="359" alt="image" src="https://github.com/liberize/ssc/assets/9167240/071e646d-a12e-41be-ab04-070766c7e476">

Thanks!

**Comment by liberize** [comment]
It's not possible unless you compile a  modified version of zsh on your own.

**Comment by liberize** [comment]
However, it's possible to hide /bin/zsh (but not /dev/fd/3) from command line. Read REAME.md and examples for -e flag.

**Comment by liberize** [comment]
And currently no other option to do this without embedding.

**Comment by liberize** [comment]
By the way, `/bin/zsh /dev/fd/3` is a normal process name. It's the same name as shell process substitution. Try `/bin/zsh <(cat script.sh)` and grep the process name.

**Comment by liberize** [comment]
Added `-i` flag to specify real interpreter path which can be different from shebang.
