### ISSUE TITLE
Header 'wordexp.h' not found using Termux

### ISSUE THREAD

**Issue by Rem01Gaming** [liberize/ssc#11]
This happen while using Termux for compile a shell script, as my attempts to make a working binary on Android environment since binary that compiled on linux won't work in Android, throwing error `env: exec mtkfest: No such file or directory`.

```bash
$ bash ssc -u mtkfest mtkfest.x
mtkfest.cpp:10:10: fatal error: 'wordexp.h' file not found
   10 | #include <wordexp.h>
      |          ^~~~~~~~~~~
1 error generated.
```

**Comment by liberize** [comment]
I haven't tested it on android termux environment.
Try installing libandroid-wordexp:
https://github.com/termux/libandroid-support/issues/8

**Comment by Rem01Gaming** [comment]
That's kinda works but it throws new errors, now from ld.lld.

```bash
$ bash ssc -u mtkfest mtkfest.x
ld.lld: error: undefined symbol: wordexp
>>> referenced by mtkfest.cpp
>>>               /data/data/com.termux/files/usr/tmp/mtkfest-b0ba19.o:(main)

ld.lld: error: undefined symbol: wordfree
>>> referenced by mtkfest.cpp
>>>               /data/data/com.termux/files/usr/tmp/mtkfest-b0ba19.o:(main)
g++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by liberize** [comment]
Try 
`LDFLAGS="-landroid-wordexp" ./ssc ...`

**Comment by Rem01Gaming** [comment]
Thanks working fine now, I've submitted #12 for add Android support.
I will use ssc instead she for my projects now.
