### ISSUE TITLE
rc.4 has no CXXFLAGS set

### ISSUE THREAD

**Issue by TJokiel** [liberize/ssc#13]
Please add CXXFLAGS for rc4 otherwise cross compilation fails when '-s' (static) and '-4' flags are used.

Please change:
`[ -f ./rc4 ] || $CXX -std=$CXX_STANDARD "$DIR/rc4.cpp" -o rc4 || exit 1`

to:
`[ -f ./rc4 ] || $CXX $CXXFLAGS -std=$CXX_STANDARD "$DIR/rc4.cpp" -o rc4 || exit 1`

Thank you

**Comment by liberize** [comment]
I think the problem is $CXX is a cross compiler, so the generated rc4 binary cannot run on host os.
I'll change $CXX to host compiler.

**Comment by liberize** [comment]
Please pull latest code and test it.

**Comment by TJokiel** [comment]
Problem resolved.
