### ISSUE TITLE
/dev/fd symlink creation

### ISSUE THREAD

**Issue by TJokiel** [liberize/ssc#14]
When running the binary in the embedded environment I need to create the symlink manually after mounting devtmpfs:
`ln -s /proc/self/fd /dev/fd`

Perhaps SSC could create this link by itself if its missing?
Once symlink is in place then binary works as expected.

**Comment by liberize** [comment]
I'll add some checking for existence of /dev/fd/ and /proc/self/fd/, and choose the right one at runtime.

**Comment by liberize** [comment]
Please pull latest code and test it.

**Comment by TJokiel** [comment]
Problem resolved.
