### ISSUE TITLE
脚本内执行source命令

### ISSUE THREAD

**Issue by xiaxiaxaia** [liberize/ssc#16]
原脚本是source了一个脚本，以加载一些函数，现在这两个脚本都被加密了，由于它们都是二进制文件，所以无法正常source

**Comment by xiaxiaxaia** [comment]
![1709028271427](https://github.com/liberize/ssc/assets/85777815/b242e8c3-a0be-4206-b94c-442490dff1b3)

**Comment by liberize** [comment]
目前只能建议你复制到一个脚本里面。

**Comment by xiaxiaxaia** [comment]
好的谢谢
