### ISSUE TITLE
Enhancement: mount proc automatically

### ISSUE THREAD

**Issue by TJokiel** [liberize/ssc#18]
Hi Paul,

Can we mount proc filesystem automatically in case:

a) its not mounted already
b) ssc script was run as root

Right now I need to use another utility to mkdir /proc and mount 'proc' filesystem before I can use SSC compiled script.

Thank you.

**Comment by liberize** [comment]
What command do you use to mount the /proc filesystem?

**Comment by TJokiel** [comment]
This is the C code which I use successfully (mind that I'm not a C coder):

```
#include <stdio.h>
#include <string.h>

main() {

  char folder[256];
  char name[20];
  strcpy(folder,"/proc");
  mkdir(folder,0755);

  char mount_point[]="proc";
  char proc[]="proc";
  char filesystype[9]="proc";

  setvbuf(stdout, NULL, _IOLBF, 0);
  if (mount(mount_point, proc, filesystype, 0, 0, NULL) != 0)
    perror("mount() error");
}

```

for shell it would be:
```

#!/bin/sh

mkdir -p /proc
mount -nt proc proc /proc
```

Thnaks

**Comment by liberize** [comment]
Try latest code.

**Comment by TJokiel** [comment]
Works perfectly well - thank you.
