### ISSUE TITLE
How to find the real path of the interpreter

### ISSUE THREAD

**Issue by TJokiel** [liberize/ssc#19]
Hello,

I'm compiling my script with following options:
`ssc -0 -4 -u -s -r -i /bin/bash -e ./bash script.src script`

I know the interpreter gets unpacked to a subfolder in /tmp upon execution.
Is there a way to find a real path to the unpacked interpreter from the script?

I want to run MD5 sum check on it before executing the main part of the script.

Or maybe to force a path where the interpreter should be unpacked? 
(must overwrite the existing file)

Thanks

**Comment by liberize** [comment]
Please read README and examples.
Btw, -i has no effect if -e is present.

**Comment by liberize** [comment]
There is $SSC_INTERPRETER_PATH.
