### ISSUE TITLE
stdin from pipe

### ISSUE THREAD

**Issue by suntong** [liberize/ssc#2]
The design of ssc is significantly secure than shc, but one major question --

can the script read from pipe as input, to act as a filter?
I.e., can the compiled binary _"behaves exactly like the original script"_?

**Comment by liberize** [comment]
It's a limitation, indeed.
Maybe you can read from /dev/tty to workaround this. (untested)
ref: https://superuser.com/questions/834502/possible-to-get-a-bash-script-to-accept-input-from-terminal-if-its-stdin-has-bee

**Comment by liberize** [comment]
It's a limitation, indeed.
Try dev branch, which pipes script from child to parent, and doesn't use stdin.

**Comment by liberize** [comment]
dev branch merged to master and deleted.
