### ISSUE TITLE
“parse shebang failed: Success”

### ISSUE THREAD

**Issue by shenzhigang** [liberize/ssc#21]
Compiling in Termux, it runs normally when execute the encrypted file directly, but when placed in `/data/local/tmp` on the same phone to run, it prompts: "parse shebang failed: Success." The shell script is as follows:

```sh
#!/system/bin/sh
echo "hello world"
```

![image](https://github.com/liberize/ssc/assets/8005935/888b887a-0cd8-4e9b-a1e3-e67c2be1402b)

**Comment by liberize** [comment]
I can't reproduce this issue.
Without root, I got `permission denied` when copying binary to /data/local/tmp.
With root, it runs ok.
![image](https://github.com/liberize/ssc/assets/3303478/4193418d-11cf-4a00-837d-0f1797115286)

What arguments are you using?

**Comment by shenzhigang** [comment]
> I can't reproduce this issue. Without root, I got `permission denied` when copying binary to /data/local/tmp. With root, it runs ok. ![image](https://private-user-images.githubusercontent.com/3303478/322258627-4193418d-11cf-4a00-837d-0f1797115286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMDM5MzIsIm5iZiI6MTcxMzEwMzYzMiwicGF0aCI6Ii8zMzAzNDc4LzMyMjI1ODYyNy00MTkzNDE4ZC0xMWNmLTRhMDAtODM3ZC0wZjE3OTcxMTUyODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTQwNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg0YmY2ODE2OGE2MmU3YjJjNmE0ZGZjMGM0NWUxZWFkZWI2MzNlY2E4YjMzMGNmN2QyNjljNTk0MDQyYTI0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yrL28bsaP0p9aIwFamiZm19zvPQx9uEaxANIf8Y6ocE)
> 
> What arguments are you using?

./ssc ./test.sh aaa

**Comment by liberize** [comment]
Close as can't repro.
