### ISSUE TITLE
asking for cross platform

### ISSUE THREAD

**Issue by scriptvpskita** [liberize/ssc#22]
apt install g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
CROSS_COMPILE=aarch64-linux-gnu- ./ssc script binary

is this willl make a script support and run for aarch64 & x64/86_64 ?

**Comment by liberize** [comment]
No, this generates binary that runs on aarch64 only.

**Comment by scriptvpskita** [comment]
can this script do multi cross multi architecture?
cross aarch64 & x64/86_64 ?

**Comment by liberize** [comment]
You can cross compile binary for any platform, but you have to distribute multiple binaries separately for different platforms. It's os thing, not ssc's limit.

**Comment by scriptvpskita** [comment]
hello, i have a problem when compile on Ubuntu 23.10 x86_64

when i run the script it shown error :
_Hit:1 http://mirrors.digitalocean.com/ubuntu mantic InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu mantic-updates InRelease
Hit:3 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu mantic-backports InRelease
Err:1 http://mirrors.digitalocean.com/ubuntu mantic InRelease
  Waited for apt-key but it wasn't there
Err:2 http://mirrors.digitalocean.com/ubuntu mantic-updates InRelease
  Waited for apt-key but it wasn't there
Err:3 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
  Waited for apt-key but it wasn't there
Err:4 http://mirrors.digitalocean.com/ubuntu mantic-backports InRelease
  Waited for apt-key but it wasn't there_


cmd : ./ssc -s -u script binary

**Comment by liberize** [comment]
It seems to be an apt problem, but ssc doesn't call apt.

**Comment by liberize** [comment]
You have to find out why apt is called.
Run ssc with -v and paste full output here.

**Comment by liberize** [comment]
Or are the error messages shown when you are installing packages with apt rather than running ssc?

**Comment by scriptvpskita** [comment]
The error occurred after I ran a script that was compiled with SSC. Inside the script, there's a package installation using apt.

**Comment by scriptvpskita** [comment]
thanks, after doing that. now its normal !
