### ISSUE TITLE
Block Structures in Configuration Files Get Flattened After Encryption

### ISSUE THREAD

**Issue by scriptvpskita** [liberize/ssc#24]
There is an issue when a Bash script is encrypted using ./ssc -s -u

if it contains any block structures inside, such as JSON, nginx.conf, etc.
The structure changes to a single line

This problem also affects other configuration files with block structures, such as nginx.conf, etc.

could you please fix the issue ?
thanks

example block structures inside bash script:
cat > example.json << END
`{`
`    "log": {`
`      "access": "/var/log/xray/access.log",`
`      "error": "/var/log/xray/error.log",`
`      "loglevel": "info"`
`  }`
END

output run script encrypted:
{
"log": {
"access": "/var/log/xray/access.log",
"error": "/var/log/xray/error.log",
"loglevel": "info"
}

**Comment by liberize** [comment]
I can't reproduce it. Please provide a detailed example.

**Comment by scriptvpskita** [comment]
all json or anything on inside block structures Will get flatted. like this

example.sh

#!/bin/bash

cat > example.json << END 
`{`
`  "nama": "Budi Santoso",`
`  "umur": 30,`
`  "email": "budi.santoso@example.com",`
`  "alamat": {`
`    "jalan": "Jalan Mawar No. 123",`
`    "kota": "Jakarta",`
 `   "kode_pos": "12345"`
`#dont_delete`
`  },`
`  "telepon": [`
`    "081234567890"`
`  ],`
`  "status_aktif": true`
`}`
END

compile script use ssc
./ssc -s -u "example.sh" "examplee.sh"

then run the script
after run. cek example.json (cat example.json)
the output always get flatted and all symbol # get removed

you can try with anything json. so its easy to reproduce

**Comment by liberize** [comment]
No, still cannot reproduce.
![ttt](https://github.com/liberize/ssc/assets/3303478/d7225032-8a02-48f6-af61-7ebfbdb5bf88)
