### ISSUE TITLE
关于-e

### ISSUE THREAD

**Issue by CN-obi** [liberize/ssc#26]
/tmp/ssc/
必须手动创建。。。。工具没有自动创建这个目录
mux/files/home/ssc/二进制; exit &>/dev/null        <
create output directory failed: No such file or directory

[进程已结束 (error 1) - 按回车关闭]

**Comment by liberize** [comment]
你的/tmp是不是权限有问题

**Comment by liberize** [comment]
这里是有创建/tmp/ssc的：
https://github.com/liberize/ssc/blob/80bbfba4cf855027f4d1e317cb65b0575ea3a193/src/embed.h#L54
