### ISSUE TITLE
libandroid-wordexp.a

### ISSUE THREAD

**Issue by CN-obi** [liberize/ssc#27]
我修改了创建位置已经解决了问题，还一个问题就是libandroid-wordexp.so，你有静态库吗？libandroid-wordexp.a

**Comment by CN-obi** [comment]
如何与你联系？TG？QQ？

**Comment by liberize** [comment]
用包管理器安装

**Comment by CN-obi** [comment]
> 用包管理器

包管理器是什么？

**Comment by CN-obi** [comment]
包管理器没有静态库，换了源也没有静态库

**Comment by CN-obi** [comment]
另外这个加密防不住dump

**Comment by liberize** [comment]
有没有libandroid-wordexp-static这个包？
如果包管理器没有，就自己源码编译。
