### ISSUE TITLE
Is it possible: shebang that begins with env

### ISSUE THREAD

**Issue by suntong** [liberize/ssc#28]
https://github.com/liberize/ssc/blob/80bbfba4cf855027f4d1e317cb65b0575ea3a193/examples/1_without_shebang/test.bash#L1-L2

Many *nix based script use shebang that begins with env, like for my perl script, I'll begin them with

`#! /usr/bin/env -S perl -p`

Would such scripts be supported, even if they don't have the proper extension with them? thx

**Comment by liberize** [comment]
Yes, it's supported.

**Comment by suntong** [comment]
thanks, I'll give it try.

**Comment by suntong** [comment]
BTW, internally, would the compiled executable call `env` or call the interpreter directly?

**Comment by liberize** [comment]
Only support /usr/bin/env without any flags...

**Comment by liberize** [comment]
Currently, calls interpreter directly.

**Comment by suntong** [comment]
> Only support /usr/bin/env without any flags...

You meant without any flags to env or to the interpreter instead?

As Perl scripts uses to put more flags on the shebang line.

**Comment by liberize** [comment]
Without any flags to env.
Currently if /usr/bin/env is found, it will be dropped directly.
