### ISSUE TITLE
embed interpreter

### ISSUE THREAD

**Issue by suntong** [liberize/ssc#29]
https://github.com/liberize/ssc/blob/80bbfba4cf855027f4d1e317cb65b0575ea3a193/examples/4_embed_interpreter/test_busybox.sh#L5-L7

What does the _"in this case"_ mean here?
Does it means only for busybox? 
Why the test bash-static one has to do it _in the end_ please? thx.

**Comment by liberize** [comment]
It means... if you need to call the interpreter in your script, you obviously can't remove it at the beginning.

**Comment by suntong** [comment]
Hmm, to make it crystal clear, in this script,

https://github.com/liberize/ssc/blob/master/examples/4_embed_interpreter/test_bash_static.sh

is it calling the interpreter?  
OK to remove it at the beginning of the script as well?

and would you give an example when  a script call the interpreter please? thx.

**Comment by liberize** [comment]
...script calls interpreter, is like doing this in your script:
sh -c 'command'
