### ISSUE TITLE
A bug or feature? 

### ISSUE THREAD

**Issue by hpc4you** [liberize/ssc#3]
There are two scripts: 
- scriptA
- scriptB, scriptB is called within scriptA with full path. 

Use **ssc** to compile scriptA, got scriptA.x, and compile scriptB, got scriptB.x.  

Run the cmd, `./scriptA`, and I got the following message, 

```
/bin/bash: --: invalid option
Usage:	/bin/bash [GNU long option] [option] ...
	/bin/bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--pretty-print
	--rcfile
	--rpm-requires
	--restricted
	--verbose
	--version
Shell options:
	-ilrsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
```

While the same script works fine with **shc**.

**Comment by liberize** [comment]
it's a bug.
should be fixed with commit 163ebd0
