### ISSUE TITLE
In promoting ssc

### ISSUE THREAD

**Issue by suntong** [liberize/ssc#31]
Hi @liberize, 

Would you like to promote ssc, putting it into the spotlight that'll attract attention hundreds times more?

There is _some_ likelihood that we'll [get a shc GH organization name](https://github.com/orgs/community/discussions/136303), if we succeeded in doing so, would you like to move [ssc](https://github.com/liberize/ssc) under it to get more exposure, or you'd rather keep it here in private name?

**Comment by suntong** [comment]
impossible!

**Comment by suntong** [comment]
Well, we DO have a new home -- https://github.com/NextSHC, let me know if you're interested...

**Comment by liberize** [comment]
What's the point of moving it to an organization? I don't think it'll bring more exposure... Anyway, you can always fork one in your organization.

**Comment by suntong** [comment]
up to you, was only trying to help.
