### ISSUE TITLE
Compile error when --static is used

### ISSUE THREAD

**Issue by lightaffaire** [liberize/ssc#33]
$ ssc --static --fix-argv0 /usr/local/bin/test.sh test-ssc.sh

/usr/bin/ld: cannot find -lstdc++: No such file or directory
/usr/bin/ld: cannot find -lm: No such file or directory
/usr/bin/ld: cannot find -lc: No such file or directory
collect2: error: ld returned 1 exit status

Without the --static flag it compiles fine and works ok.

**Comment by liberize** [comment]
what os are you using?

**Comment by liberize** [comment]
and what compiler version?

**Comment by liberize** [comment]
Please run with -v and paste the output here.

**Comment by lightaffaire** [comment]
RUN: /usr/local/src/ssc-master/ssc --fix-argv0 --static -v /content/tmp/generate-shell-binary.d/db-inline /content/bin/shell-binary/db

+ CXXFLAGS=' -DFIX_ARGV0 -static -static-libgcc -static-libstdc++ -v'
+ shift
+ '[' -n /content/tmp/generate-shell-binary.d/db-inline ']'
+ case "$1" in
+ POSITIONAL_ARGS=' "/content/tmp/generate-shell-binary.d/db-inline"'
+ shift
+ '[' -n /content/bin/shell-binary/db ']'
+ case "$1" in
+ POSITIONAL_ARGS=' "/content/tmp/generate-shell-binary.d/db-inline" "/content/bin/shell-binary/db"'
+ shift
+ '[' -n '' ']'
+ eval set -- '"/content/tmp/generate-shell-binary.d/db-inline"' '"/content/bin/shell-binary/db"'
++ set -- /content/tmp/generate-shell-binary.d/db-inline /content/bin/shell-binary/db
+ '[' -n '' -o 2 '!=' 2 ']'
++ dirname /usr/local/src/ssc-master/ssc
+ DIR=/usr/local/src/ssc-master/src
+ '[' -z '' ']'
+ CXX=g++
+ '[' -z '' ']'
+ LD=ld
+ '[' -z '' ']'
+ STRIP=strip
+ CXX_STANDARD=c++14
+ case "$(uname -s)" in
++ uname -s
+ MACHINE=Linux
++ command -v termux-info
+ '[' -x '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ g++ -v
+ grep clang
+ CXXFLAGS=' -DFIX_ARGV0 -static -static-libgcc -static-libstdc++ -v -fconstexpr-loop-limit=1073741824 -fconstexpr-ops-limit=1073741824'
+ perl -pe 's|SCRIPT_FILE_NAME|/content/tmp/generate-shell-binary.d/db-inline|g; s|SCRIPT_CONTENT|`cat '\''/content/tmp/generate-shell-binary.d/db-inline'\''`|ge' /usr/local/src/ssc-master/src/main.cpp
+ '[' -n '' ']'
+ g++ -I/usr/local/src/ssc-master/src -std=c++14 -DFIX_ARGV0 -static -static-libgcc -static-libstdc++ -v -fconstexpr-loop-limit=1073741824 -fconstexpr-ops-limit=1073741824 /content/tmp/generate-shell-binary.d/db-inline.cpp -o /content/bin/shell-binary/db
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-libstdcxx-backtrace --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-12.3.1-20230508/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-offload-defaulted --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.3.1 20230508 (Red Hat 12.3.1-1) (GCC) 
COLLECT_GCC_OPTIONS='-I' '/usr/local/src/ssc-master/src' '-std=c++14' '-D' 'FIX_ARGV0' '-static' '-static-libgcc' '-v' '-fconstexpr-loop-limit=1073741824' '-fconstexpr-ops-limit=1073741824' '-o' '/content/bin/shell-binary/db' '-mtune=generic' '-march=x86-64' '-dumpdir' '/content/bin/shell-binary/db-'
 /usr/libexec/gcc/x86_64-redhat-linux/12/cc1plus -quiet -v -I /usr/local/src/ssc-master/src -D_GNU_SOURCE -D FIX_ARGV0 /content/tmp/generate-shell-binary.d/db-inline.cpp -quiet -dumpdir /content/bin/shell-binary/db- -dumpbase db-inline.cpp -dumpbase-ext .cpp -mtune=generic -march=x86-64 -std=c++14 -version -fconstexpr-loop-limit=1073741824 -fconstexpr-ops-limit=1073741824 -o /tmp/cc3e6LTl.s
GNU C++14 (GCC) version 12.3.1 20230508 (Red Hat 12.3.1-1) (x86_64-redhat-linux)
	compiled by GNU C version 12.3.1 20230508 (Red Hat 12.3.1-1), GMP version 6.2.1, MPFR version 4.1.0-p13, MPC version 1.2.1, isl version isl-0.24-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/12/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/12/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/src/ssc-master/src
 /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12
 /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/x86_64-redhat-linux
 /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/backward
 /usr/lib/gcc/x86_64-redhat-linux/12/include
 /usr/local/include
 /usr/include
End of search list.
GNU C++14 (GCC) version 12.3.1 20230508 (Red Hat 12.3.1-1) (x86_64-redhat-linux)
	compiled by GNU C version 12.3.1 20230508 (Red Hat 12.3.1-1), GMP version 6.2.1, MPFR version 4.1.0-p13, MPC version 1.2.1, isl version isl-0.24-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 7da7486e00808c7add003c8881d4a657
COLLECT_GCC_OPTIONS='-I' '/usr/local/src/ssc-master/src' '-std=c++14' '-D' 'FIX_ARGV0' '-static' '-static-libgcc' '-v' '-fconstexpr-loop-limit=1073741824' '-fconstexpr-ops-limit=1073741824' '-o' '/content/bin/shell-binary/db' '-mtune=generic' '-march=x86-64' '-dumpdir' '/content/bin/shell-binary/db-'
 as -v -I /usr/local/src/ssc-master/src --64 -o /tmp/ccIziaKR.o /tmp/cc3e6LTl.s
GNU assembler version 2.38 (x86_64-redhat-linux) using BFD version version 2.38-27.fc37
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/12/:/usr/libexec/gcc/x86_64-redhat-linux/12/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/12/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/12/:/usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/12/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-I' '/usr/local/src/ssc-master/src' '-std=c++14' '-D' 'FIX_ARGV0' '-static' '-static-libgcc' '-v' '-fconstexpr-loop-limit=1073741824' '-fconstexpr-ops-limit=1073741824' '-o' '/content/bin/shell-binary/db' '-mtune=generic' '-march=x86-64' '-dumpdir' '/content/bin/shell-binary/db.'
 /usr/libexec/gcc/x86_64-redhat-linux/12/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/12/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/12/lto-wrapper -plugin-opt=-fresolution=/tmp/ccRCGwf5.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc --build-id --no-add-needed --hash-style=gnu -m elf_x86_64 -static -o /content/bin/shell-binary/db /usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/12/crtbeginT.o -L/usr/lib/gcc/x86_64-redhat-linux/12 -L/usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/12/../../.. /tmp/ccIziaKR.o -lstdc++ -lm --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc/x86_64-redhat-linux/12/crtend.o /usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crtn.o
/usr/bin/ld: cannot find -lstdc++: No such file or directory
/usr/bin/ld: cannot find -lm: No such file or directory
/usr/bin/ld: cannot find -lc: No such file or directory
collect2: error: ld returned 1 exit status
+ exit 1

**Comment by liberize** [comment]
```bash
yum install glibc-static libstdc++-static
```

**Comment by lightaffaire** [comment]
Thank you. Installed the missing libs and --static worked.

**Comment by liberize** [comment]
the package names are different for different systems, it's hard to list them here.

**Comment by lightaffaire** [comment]
maybe list them for 1. redhat/fedora and 2. debian/ubuntu ?  anything listed will be a help to others and cut down on support issues which costs you time.
