### ISSUE TITLE
option --rc4 ends up being generated as a binary file!

### ISSUE THREAD

**Issue by lightaffaire** [liberize/ssc#34]
If one specifies -4 or --rc4 as an option to ssc it ends up being a binary file on the disk and is not parsed as an option:

$ ssc -4 --fix-argv0 --static --untraceable /tmp/db db.bin
or
$ ssc --rc4 --fix-argv0 --static --untraceable /tmp/db db.bin

both produce:

-rwxr-xr-x 1 root root  2496864 Sep  6 13:09 db.bin*
-rwxr-xr-x 1 root root    17248 Sep  6 13:09 rc4*

$ file *
db.bin: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=b43b917b9f63bea841a53b88d441a6098f6b10d8, for GNU/Linux 3.2.0, stripped
rc4:    ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f7d848917ece1978a342a7eab4a2750c3abea7a5, for GNU/Linux 3.2.0, not stripped

**Comment by liberize** [comment]
if -4 is used, it has to generate the rc4 tool first, then use it to encrypt the script.

**Comment by lightaffaire** [comment]
that needs documenting...

so i have to run the command twice?  first time it generates the rc4 binary and the second time it uses the rc4 in the generation of the script to binary file ?

**Comment by liberize** [comment]
> if -4 is used, ssc has to generate the rc4 tool first, then use it to encrypt the script.

It's done internally in ssc.

**Comment by liberize** [comment]
I'll modify ssc to remove the generated rc4 tool to avoid confusion.

**Comment by liberize** [comment]
Now the intermediate rc4 tool will be removed before script exit.
