### ISSUE TITLE
whats wrong with new ssc ?

### ISSUE THREAD

**Issue by scriptvpskita** [liberize/ssc#37]
i dont know why, when i try

./ssc -s -u "script" "script"
output
In file included from /root/ssc/v1/setup.sh.cpp:17:
/root/ssc/./src/untraceable.h: In function ‘void check_debugger()’:
/root/ssc/./src/utils.h:19:69: warning: format not a string literal and no format arguments [-Wformat-security]
   19 | #define LOGE(fmt, ...)  fprintf(stderr, OBF(fmt "\n"), ##__VA_ARGS__)
      |                                                                     ^
/root/ssc/./src/untraceable.h:78:9: note: in expansion of macro ‘LOGE’
   78 |         LOGE("fork failed");
      |         ^~~~
/root/ssc/v1/setup.sh.cpp: In function ‘int main(int, char**)’:
/root/ssc/./src/utils.h:19:69: warning: format not a string literal and no format arguments [-Wformat-security]
   19 | #define LOGE(fmt, ...)  fprintf(stderr, OBF(fmt "\n"), ##__VA_ARGS__)
      |                                                                     ^
/root/ssc/v1/setup.sh.cpp:159:13: note: in expansion of macro ‘LOGE’
  159 |             LOGE("failed to parse shebang!");
      |             ^~~~
/root/ssc/./src/utils.h:19:69: warning: format not a string literal and no format arguments [-Wformat-security]
   19 | #define LOGE(fmt, ...)  fprintf(stderr, OBF(fmt "\n"), ##__VA_ARGS__)
      |                                                                     ^
/root/ssc/v1/setup.sh.cpp:211:30: note: in expansion of macro ‘LOGE’
  211 |             default:         LOGE("unknown format!"); return 4;
      |                              ^~~~
/root/ssc/./src/utils.h:19:69: warning: format not a string literal and no format arguments [-Wformat-security]
   19 | #define LOGE(fmt, ...)  fprintf(stderr, OBF(fmt "\n"), ##__VA_ARGS__)
      |                                                                     ^
/root/ssc/v1/setup.sh.cpp:241:9: note: in expansion of macro ‘LOGE’
  241 |         LOGE("failed to create pipe!");
      |         ^~~~
/root/ssc/./src/utils.h:19:69: warning: format not a string literal and no format arguments [-Wformat-security]
   19 | #define LOGE(fmt, ...)  fprintf(stderr, OBF(fmt "\n"), ##__VA_ARGS__)
      |                                                                     ^
/root/ssc/v1/setup.sh.cpp:249:9: note: in expansion of macro ‘LOGE’
  249 |         LOGE("failed to fork process!");
      |         ^~~~

**Comment by liberize** [comment]
It's just some compiler warnings.
Try `CXXFLAGS="-Wno-format" ./ssc -s -u "script" "script"`.

**Comment by liberize** [comment]
Please pull latest code and see if the warnings are gone.

**Comment by scriptvpskita** [comment]
hello its gone now !

thanks
