### ISSUE TITLE
Building dependencies

### ISSUE THREAD

**Issue by suntong** [liberize/ssc#4]
what packages are necessary to successfully build the binary pls?

UTSL, I saw perl, g++, and clang++?

I.e., `clang` is _"C, C++ and Objective-C compiler"_, if I have clang do I still need `g++`, or vice versa?

I.e., what are the minimum packages necessary for building under Debian and MacOS (homebrew & macport) please?

Thanks

**Comment by liberize** [comment]
Perl is builtin on almost every linux and macOS, so not mentioned.
As for g++ or clang++, choose one of them, usaually use g++ for linux and clang++ for macOS.

Build under debian:
Install g++

Build under macOS:
Install Xcode command line tools (which contains clang++).
Or use g++ from homebrew (untested).

**Comment by liberize** [comment]
I changed the ssc script to always use g++.
Howerver, it should still work with Xcode command line tools which provides g++ that symlinked to clang++.
