### ISSUE TITLE
please help!

### ISSUE THREAD

**Issue by RidwanzAnphelibelll** [liberize/ssc#40]
how to decrypt it from the encrypted result using -u -s -e method? I want to decrypt it because my original files have been lost.

**Comment by liberize** [comment]
I didn't try but perhaps the following steps will do. Right now -e flag doesn't encrypt the interpreter, maybe you can edit the embeded interpreter inside the binary.

1. forge an interpreter, a wrapper script to print your script content will do.
2. open your binary with an hex editor, find the second occurrence of byte sequence 7f 45 4c 46, which is the start code of en elf file.
3. replace it and the following bytes with your forged interpreter.
4. save and run the modified binary.

**Comment by liberize** [comment]
I've tested, it works.

**Comment by RidwanzAnphelibelll** [comment]
Can you provide the decryption file for me?

**Comment by liberize** [comment]
What file? Have you tried it?

**Comment by liberize** [comment]
Sorry I just decided not to provide this kind of help for free. It's not my responsibility, and I'm getting busy.

**Comment by liberize** [comment]
This method doesn't work anymore with latest ssc.
