### ISSUE TITLE
Hide commands in the processlist

### ISSUE THREAD

**Issue by MoBlockbuster** [liberize/ssc#41]
Does ssc has a possibility to hide the bashscript commands in the proccesslist on linux?

You can recreate the issue.

Create a script with following content:

#!/bin/bash
sleep 100000

after you create the binary, you can see the sleep command in the processlist on linux with ps aux | grep sleep.

Any solution to hide the commands?

Cheers

**Comment by liberize** [comment]
I'll suggest you using busybox, it provides a way to use bulitin applets instead of external commands. See the example of embedding interpreter.
