### ISSUE TITLE
What is different from shc?

### ISSUE THREAD

**Issue by fengmao31** [liberize/ssc#43]
I use shc in the past project. Shc is not easy use to link external dynamic library. What is different from shc?

**Comment by liberize** [comment]
Have you read README?

**Comment by fengmao31** [comment]
I read it. You say your inspiration come from shc. Also you list many funtions in your project. 

But it doesn't show an advantage intuitively.

**Comment by liberize** [comment]
ssc is nothing like shc, except for similar goal.
1. provides better source code protection without the cost of portability
2. support embedding data to binary
3. support almost any script language
4. support almost any shebang and any interpreter
5. no limitation on script length
If none of these is an advantage to you, then I suggest you sticking with shc.

**Comment by fengmao31** [comment]
Forgive my poor English. Your project is good. I just want to know the advantage clearly rather than shc.

**Comment by liberize** [comment]
我没有完整看过shc的代码，但是ssc至少解决了它的issue里提到的大部分的问题。
文档有中文版，如果你有什么具体的不明白的地方，可以单独提出来讨论。

**Comment by fengmao31** [comment]
> 我没有完整看过shc的代码，但是ssc至少解决了它的issue里提到的大部分的问题。 文档有中文版，如果你有什么具体的不明白的地方，可以单独提出来讨论。

好的。谢谢你。项目很棒。我之前踩过shc的坑，也希望有开源项目能够更方便使用。
