### ISSUE TITLE
Is it possible to run bin file generated as non root or sudoer user?

### ISSUE THREAD

**Issue by Ketchup31** [liberize/ssc#5]
When I launch the bin file generated by ssc, I need to be at least sudoer, that I would like to avoid as non root or sudoer user should launch the bin file. How I can do that ? Do I have any parameters that I need to set when I launch ssc ?
For information, I compile bash scripts.
Thank you for your reply.

**Comment by liberize** [comment]
Maybe it has something to do with ptrace.
I'll test it and add a switch.

**Comment by liberize** [comment]
Added -u switch (not enabled by default), see README.

**Comment by Ketchup31** [comment]
Hello,
Just to thank you for a so fast update. Please could you tell me in some words what means the -s (static) option?
Thank you.

**Comment by liberize** [comment]
`-s` means the binary is linked statically, no glibc ot libstdc++ dependency, thus more portable.
without `-s`, the binary cannot run on system with lower glibc version.

**Comment by Ketchup31** [comment]
OK Understood. Thank you. Have a great day.

**Comment by liberize** [comment]
I've added a non-root anti-tracing logic.
It should be ok to enable `-u` and run without root now.

**Comment by Ketchup31** [comment]
Thank you !!!
