### ISSUE TITLE
error basename

### ISSUE THREAD

**Issue by antonellocaroli** [liberize/ssc#9]
ho uno script shell dove all'interno mi serve recuperare il nome dello script, esempio:

```
#!/bin/bash
script_name=$(basename "$0")
echo "$script_name"
```

```
./test.sh
test.sh

ssc -u test.sh test
./test
3
```

once the script has been compiled with ssc, it seems that it no longer retrieves basename... how can this be remedied?

Thanks

**Comment by liberize** [comment]
Have you tried -0 flag？
Read README.md plz.

**Comment by antonellocaroli** [comment]
perfect, it works.

Thank you
